### ISSUE TITLE
Optional dependency OdesPy

### ISSUE THREAD

**Issue by khinsen** [rajeshrinet/pystokes#3]
The instructions for installation from source mention OdesPy as an optional dependency, but don't say what difference OdesPy makes. Does it add functionality? Improve performance? As a JOSS reviewer, should I test PyStokes with or without OdesPy?

**Comment by rajeshrinet** [comment]
@khinsen, OdesPy is not essentially for reviewing the code. OdesPy has been suggested as an optional dependency as it provides various fixed-step and adaptive-step integrators with a neat interface. The default integrator is `scipy.integrate.odeint`. Thus, once scipy is installed, all the examples of PyStokes should run.  
 
I have now added a short note on this in the README when I list OdesPy as an optional dependency. Thanks.
