### ISSUE TITLE
Update and document examples/other

### ISSUE THREAD

**Issue by khinsen** [rajeshrinet/pystokes#5]
The main example notebooks work fine, and are well documented. Under examples/other, there is additional example code that is not up to date (`benchmarks/potDipole.py` is for Python 2 and apparently a very old version of PyStokes, `mima2d` examples don't work for whatever reason). With the exception of `periodic`, there is no explanation either of what these examples are good for.

**Comment by rajeshrinet** [comment]
@khinsen thanks again for your comments. I have now made the following changes:

* `benhmark` folder has been deleted as it is already covered in the examples https://github.com/rajeshrinet/pystokes/blob/master/examples/ex7-benchmark.ipynb
* `mima2d` examples have now been updated and they now run. I have also added a README.md to that folder.

**Comment by khinsen** [comment]
Works fine, thanks! One minor issue: https://github.com/rajeshrinet/pystokes/pull/7
