### ISSUE TITLE
Provide instructions for contributing

### ISSUE THREAD

**Issue by khinsen** [rajeshrinet/pystokes#6]
JOSS requires "clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support". 2) and 3) are discussed in the README, but I didn't find guidelines for potential contributors.

**Comment by rajeshrinet** [comment]
@khinsen I have now added a new file: https://github.com/rajeshrinet/pystokes/blob/master/CONTRIBUTING.md with a brief guidelines for potential contributors.
