### ISSUE TITLE
Dependencies not specified in setup.py

### ISSUE THREAD

**Issue by fcooper8472** [rajeshrinet/pystokes#9]
Sorry for another (similar) issue!

When following instructions to install from a checkout of the repo:
```
>> git clone https://github.com/rajeshrinet/pystokes.git
>> cd pystokes
>> python setup.py install
```
I am unable to 
```
>> make test
```
because Matplotlib is missing.

Not sure where the requirements are currently specified: matplotlib is in the `requirements.txt` it [looks as though](https://packaging.python.org/discussions/install-requires-vs-requirements/) `setup.py` does not look in there by default.

I'm not sure exactly how to solve this.  Easiest would be to document for users to run:
```
pip install -r requirements.txt
```
Else if using pip to install you could specify `install_requires` in `setup.py` (which I see is currently commented out).

**Comment by rajeshrinet** [comment]
@fcooper8472 I have now updated `setup.py` and uncommented the line. Although, I also like your suggestions on adding 

```
pip install -r requirements.txt
```

in the readme. Done that. Thanks!

**Comment by fcooper8472** [comment]
@rajeshrinet Can confirm it's now working for me when following the instructions in the README.  Thanks!
